
name: Deploy Functions
on: workflow_dispatch
  inputs:
    deploy_only:
      description: 'firebase deploy --only what?'
      required: true
      default: 'functions'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/functions/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: npm ci
        run: npm ci && cd functions && npm ci
      - name: Create SA key
        run: echo '${{ secrets.FIREBASE_FUNCTIONS_SERVICE_ACCOUNT }}' > $HOME/gcloud.json
      - name: Deploy Cloud Functions
        run: export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json && npx firebase-tools deploy --only functions